      - name: Debug PAT_TOKEN
        run: |
          if [ -z "${{ secrets.PAT_TOKEN }}" ]; then
            echo "PAT_TOKEN is empty"
          else
            echo "PAT_TOKEN is set"
          fi

      - name: Set up Git credentials
        run: |
          git config user.name "github-actions"
          git config user.email "actions@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.PAT_TOKEN }}@github.com/wjdehdgur/my-project.git
